import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { PlanProvider } from "@/context/PlanContext";
import ToastContainerWrapper from "@/components/ToastContainerWrapper";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en" 
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="bg-darkBg text-neutral-100 min-h-screen flex flex-col font-sans antialiased">
         <PlanProvider>
          <Navbar />
          <main className="flex-grow">{children}</main>
        <Footer />
          <ToastContainerWrapper />
        </PlanProvider>
      </body>
    </html>
  );
}
